" @Author: Wasif Malik (wmalik@gmail.com)
" @Reference: Some stuff taken from these awesome blog posts:
"             http://stevelosh.com/blog/2010/09/coming-home-to-vim
"             http://learnvimscriptthehardway.stevelosh.com/

" Pathogen stuff {{{
call pathogen#infect('bundle/{}')
"call pathogen#incubate()
call pathogen#helptags()
"}}}

" Absolute essentials {{{
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set nofoldenable
colorscheme jellybeans
"colorscheme distinguished
syntax on
filetype on
filetype plugin on
filetype indent on
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
"set hidden " dont really like the fact that the buffers stay open
set wildmenu
set nu
set wildmode=list:longest
set novisualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set wrap
set sidescroll=1
set textwidth=80
set formatoptions=qrn1
set listchars=tab:▸\ ,eol:¬
set smartcase
set showmatch
set noantialias

" For smart indenting
"set smartindent "'smartindent' and 'cindent' might interfere with file type
""based indentation, and should never be used in conjunction with it.
set tabstop=4
set shiftwidth=2
set expandtab "pressing tab inserts spaces
if has("gui_running")
    set mouse=a
    set guioptions=egmrt
    set guioptions-=m
    "set guifont=Inconsolata\ Medium\ 12
    set guifont=Inconsolata\ 12
    "set guifont=Neep\ 12 "did not work
    "
    " Set cursor color in different modes
    highlight Cursor guifg=black guibg=lightgreen
    highlight iCursor guibg=red ctermbg=red
    set guicursor=n-v-c:block-Cursor
    set guicursor+=i:ver25-iCursor
    set guicursor+=n-v-c:blinkon0
    "set guicursor+=i:blinkwait10
    hi StatusLine guibg=white guifg=royalblue
endif

set directory=/tmp "this is to store all sw* files in /tmp
set noincsearch
set hlsearch

set ignorecase
set colorcolumn=80
runtime! ftplugin/man.vim
" searches for a tags file in the higher level directories until it is found
" enables tag browsing no matter where the src is
set tags=./tags;/
set tags+=/home/arthur/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/tags
" highlight extra whitespace
highlight ExtraWhitespace ctermbg=blue guibg=blue
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
set tw=80
set wildignore=*.o,*~,*.beam,*.swf,*.mp3,*.jpg,*.png,ebin,.git
if filereadable(".vimrc.project")
    so .vimrc.project
endif
"}}}

" Shortcuts {{{

" shortcut to run a shell command and paste the output in a scratch buffer
command! -nargs=* -complete=shellcmd R new | setlocal buftype=nofile bufhidden=hide noswapfile  | r !<args>

" grep the word under cursor (case insensitive) in multiple directories
nmap <leader>f :R grep -sirn <c-r>=expand("<cword> *")<cr> .<cr> :set ft=sh<cr>

" zoom the current buffer (aka open the current buffer in a new tab)
nmap <leader>z :tabnew %<cr>

" shortcut to find a string in multiple src dirs, example :F something
"command! -nargs=* F new | setlocal buftype=nofile bufhidden=hide noswapfile | set ft=erlang | r !grep -sirn --exclude=tags --exclude-dir=log --exclude-dir=ebin <args> .
command! -nargs=* F new | setlocal buftype=nofile bufhidden=hide noswapfile | set ft=erlang | r !ag --vimgrep <args>

" Open a scratch buffer
command! S new | setlocal buftype=nofile bufhidden=hide noswapfile
command! T tabnew | setlocal buftype=nofile bufhidden=hide noswapfile
" Open my notes files in a new buffer and go to the last line
command! Notes tabnew ~/.notes | set filetype=markdown | %

" Get the current unix timestamp
command! Timestamp r! date \+\%s
" Get nicely formatted time stamp
nnoremap <leader>d :r! date \+\[\%Y-\%m-\%d\ \%H:\%M:\%S\]<cr>


let mapleader = ","
"inoremap jk <Esc>
nnoremap <leader>w <C-w>v<C-w>l
nnoremap <C-j> <C-w>w
nnoremap <C-k> <C-w>W
nnoremap <Backspace> <C-w>w
nnoremap <S-Backspace> <C-w>W
nnoremap <leader>n :NERDTreeToggle<CR>
nnoremap <C-l> :tabnext<CR>
nnoremap <C-h> :tabprev<CR>
nnoremap <Tab>n :tabnew<CR>
nnoremap <Tab>d :tabclose<CR>
noremap <silent> <Space> :noh<Bar>:echo<CR>
nnoremap <leader>k :set list!<CR>
nnoremap :W :w
nnoremap :Set :set
nnoremap Y 0y$
inoremap <C-a> <C-o>^
inoremap <C-e> <C-o>$
"}}}

" Mouse {{{
set mouse=a
"}}}

" Erlang {{{
"remove an erlang binary term
nnoremap <leader>B 2F<d2f>i
"ignore binary files
" remove trailing whitespace and save the file
nnoremap <leader><Space> $x<Esc>:w<CR>
"let g:erlangManPath = "/usr/share/man/man1"
"let g:erlangHighlightErrors = 0
"let g:erlangHighlightBif = 1
command! Er set ft=erlang
"}}}

" Plugin Conf {{{
let g:CommandTMaxHeight=10
"}}}

" move a line upward or downward
nnoremap - ddp
nnoremap _ ddkP

" Delete current line in insert mode
inoremap <c-d> <esc>ddi

" Convert the current word to uppercase insert mode
inoremap <C-u> <Esc>viwUea

iabbrev adn and
iabbrev @@ wmalik@gmail.com
iabbrev ldeb lager:debug("", [])
iabbrev ei error_logger:info_msg("", [])
iabbrev ew error_logger:warning_msg("", [])
iabbrev ee error_logger:error_msg("", [])
"iabbrev pgv proplists:get_value(

nnoremap <leader>ve :tabnew $MYVIMRC<cr>
nnoremap <leader>vs :source ~/.vimrc<cr>

" surround a word or a visual block with "" (doesnt work with v-line)
vnoremap <leader>" <esc>`<i"<esc>`>la"
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
inoremap <C-q> <Esc>viw<esc>a"<esc>hbi"<esc>lela
" surround a word or a visual block with {} (doesnt work with v-line)
vnoremap <leader>{ <esc>`<i}<esc>`>la{
nnoremap <leader>{ viw<esc>a}<esc>hbi{<esc>lel
inoremap <C-q> <Esc>viw<esc>a}<esc>hbi{<esc>lela
" surround a word or a visual block with {} (doesnt work with v-line)
vnoremap <leader>( <esc>`<i)<esc>`>la(
nnoremap <leader>( viw<esc>a)<esc>hbi(<esc>lel
inoremap <C-q> <Esc>viw<esc>a)<esc>hbi(<esc>lela
" surround a word or a visual block with {} (doesnt work with v-line)
vnoremap <leader>[ <esc>`<i]<esc>`>la[
nnoremap <leader>[ viw<esc>a]<esc>hbi[<esc>lel
inoremap <C-q> <Esc>viw<esc>a]<esc>hbi[<esc>lela

" surround a word or a visual block with '' (doesnt work with v-line)
vnoremap <leader>" <esc>`<i'<esc>`>la'
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel
noh
" Insert a character at the end of line
nnoremap <leader>, :normal! mqA,<esc>`q
nnoremap <leader>. :normal! mqA.<esc>`q
nnoremap <leader>; :normal! mqA;<esc>`q

" generate exuberant ctags for all directories excluding the assets directory
nnoremap <leader>ct :!ctags -R --exclude=assets *<cr>


" Notes {{{
" Taken from bare bones vim http://vimeo.com/65250028
" makes navigation easier without ctags (use gf)
" set path=**
" set suffixesadd=.erl,.hrl
" }}}


"augroup filetype_erl
    "autocmd!
    "autocmd FileType,BufNewFile,BufRead escript setlocal filetype=erlang
    "autocmd FileType,BufNewFile,BufRead *.app.src setlocal filetype=erlang
    "autocmd FileType,BufNewFile,BufRead rebar.config setlocal filetype=erlang
    "autocmd FileType,BufNewFile,BufRead *.term setlocal filetype=erlang
    "command! -nargs=* F new | setlocal buftype=nofile bufhidden=hide noswapfile | set ft=erlang | r !grep -sirn --exclude=tags --exclude-dir=log --exclude-dir=.eunit --exclude-dir=.git --exclude-dir=ebin <args> .
    "nnoremap <leader>ct :ErlangTags<cr>
    "command! -nargs=1 Erl Man 3erl <args>
    "nnoremap <leader>ei yiwoerror_logger:info_msg("<esc>pa ~p~n", [<esc>pa]),<esc>
    "vnoremap <leader>ei "myoerror_logger:info_msg("<esc>"mpa ~p~n", [<esc>"mpa]),<esc>

"augroup END

augroup filetype_html
    autocmd!
    autocmd FileType,BufNewFile,BufRead *.mustache setlocal filetype=html
    au FileType *.mustache setl sw=2 sts=2
    au FileType html setl sw=2 sts=2
augroup END

let g:ycm_python_binary_path = 'python'
augroup filetype_python
    autocmd!
    autocmd FileType,BufNewFile,BufRead *.py setlocal filetype=python
    au BufNewFile,BufRead *.py  setl tabstop=2  softtabstop=2  shiftwidth=2  textwidth=80  expandtab  autoindent  fileformat=unix
    map <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
    nnoremap <leader>o yiwoprint "<esc>pa: {}".format(<esc>pa)<esc>
augroup END

inoremap <C-h> <left>
inoremap <C-l> <right>
inoremap <C-j> <down>
inoremap <C-k> <up>
command! Z tabnew %
xnoremap . :norm.<CR>


" Move visual block
vnoremap J :m '>+1<CR>gvgv
vnoremap K :m '<-2<CR>gvgv

let g:ref_use_vimproc = 1
let g:ref_open = 'split'
let g:ref_cache_dir = expand($TMP . '/vim_ref_cache/')
nno <leader>K :<C-u>Unite ref/erlang
            \ -vertical -default-action=split<CR>


let &colorcolumn=join(range(&tw,999),",")
nnoremap & /^<C-r><C-w><cr>

set autowrite
set autowriteall

nmap <leader>p :set paste<cr>"*p:set nopaste<cr>
nmap <leader>np :set nopaste<cr>

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" local cd into the windows file
"autocmd BufEnter * silent! lcd %:p:h

" syntastic
"set statusline+=%#warningmsg#
"set statusline+=%*
"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0
let g:syntastic_python_checkers = []

set clipboard=unnamedplus

let g:ycm_key_list_select_completion=[]
let g:ycm_key_list_previous_completion=[]
let g:UltiSnipsExpandTrigger="<c-j>"

nnoremap <leader>r :RuboCop<cr>
