" @Author: Wasif Malik (wmalik@gmail.com)
" @Reference: Some stuff taken from these awesome blog posts:
"             http://stevelosh.com/blog/2010/09/coming-home-to-vim
"             http://learnvimscriptthehardway.stevelosh.com/

" Pathogen stuff {{{
call pathogen#infect('bundle/{}')
"call pathogen#incubate()
call pathogen#helptags()
"}}}

" Absolute essentials {{{
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set nofoldenable
colorscheme jellybeans
"colorscheme distinguished

syntax on
filetype on
filetype plugin on
filetype indent on
set encoding=utf-8
set scrolloff=3
set autoindent
set showmode
set showcmd
"set hidden " dont really like the fact that the buffers stay open
set wildmenu
set nu
set wildmode=list:longest
set novisualbell
set cursorline
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
set wrap
set sidescroll=1
set textwidth=80
set formatoptions=qrn1
set listchars=tab:▸\ ,eol:¬
set smartcase
set showmatch
set noantialias

" For smart indenting
"set smartindent "'smartindent' and 'cindent' might interfere with file type
""based indentation, and should never be used in conjunction with it.
set tabstop=4
set shiftwidth=2
set expandtab "pressing tab inserts spaces
if has("gui_running")
    set mouse=a
    set guioptions=egmrt
    set guioptions-=m
    set guifont=Inconsolata\ 12
    "
    " Set cursor color in different modes
    highlight Cursor guifg=black guibg=lightgreen
    highlight iCursor guibg=red ctermbg=red
    set guicursor=n-v-c:block-Cursor
    set guicursor+=i:ver25-iCursor
    set guicursor+=n-v-c:blinkon0
    hi StatusLine guibg=white guifg=royalblue
endif

set directory=/tmp "this is to store all sw* files in /tmp
set noincsearch
set hlsearch

set ignorecase
runtime! ftplugin/man.vim
" searches for a tags file in the higher level directories until it is found
" enables tag browsing no matter where the src is
set tags=./tags;/
" highlight extra whitespace
highlight ExtraWhitespace ctermbg=blue guibg=blue
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
set wildignore=*.o,*~,*.beam,*.swf,*.mp3,*.jpg,*.png,ebin,.git

"}}}

" Shortcuts {{{

" shortcut to run a shell command and paste the output in a scratch buffer
command! -nargs=* -complete=shellcmd R new | setlocal buftype=nofile bufhidden=hide noswapfile  | r !<args>

" grep the word under cursor (case insensitive) in multiple directories
nmap <leader>f :R grep -sirn <c-r>=expand("<cword> *")<cr> .<cr> :set ft=sh<cr>

" shortcut to find a string in multiple src dirs, example :F something
command! -nargs=* F new | setlocal buftype=nofile bufhidden=hide noswapfile | r !Ack --vimgrep <args>

" Open a scratch buffer
command! S new | setlocal buftype=nofile bufhidden=hide noswapfile
command! ST tabnew | setlocal buftype=nofile bufhidden=hide noswapfile

" Get the current unix timestamp
command! Timestamp r! date \+\%s
" Get nicely formatted time stamp
nnoremap <leader>d :r! date \+\%Y-\%m-\%d\ \%H:\%M:\%S<cr>
nnoremap <leader>t :r! date -d\@<C-r><C-w><cr>
nnoremap <leader>T :r! date \+\%s<cr>

let mapleader = ","
inoremap jk <Esc>
nnoremap <leader>w <C-w>v<C-w>l
nnoremap <C-j> <C-w>w
nnoremap <C-k> <C-w>W
nnoremap <leader>n :NERDTreeToggle<CR>
nnoremap <C-l> :tabnext<CR>
nnoremap <C-h> :tabprev<CR>
nnoremap <leader>l :+tabmove<CR>
nnoremap <leader>h :-tabmove<CR>
nnoremap <Tab>n :tabnew<CR>
nnoremap <Tab>d :tabclose<CR>
noremap <silent> <Space> :noh<Bar>:echo<CR>
nnoremap <leader>k :set list!<CR>
nnoremap :W :w
nnoremap :Set :set
nnoremap T :Texplore<CR>
inoremap <C-a> <C-o>^
inoremap <C-e> <C-o>$
"}}}

" Mouse {{{
set mouse=a
"}}}

" Erlang {{{
nnoremap <leader>B 2F<d2f>i
command! Er set ft=erlang
"}}}

" Plugin Conf {{{
let g:CommandTMaxHeight=10
"}}}

" move a line upward or downward
nnoremap - ddp
nnoremap _ ddkP

" Delete current line in insert mode
inoremap <c-d> <esc>ddi

" Convert the current word to uppercase insert mode
inoremap <C-u> <Esc>viwUea

iabbrev adn and
iabbrev @@ wmalik@gmail.com
iabbrev ldeb lager:debug("", [])
iabbrev ei error_logger:info_msg("", [])
iabbrev ew error_logger:warning_msg("", [])
iabbrev ee error_logger:error_msg("", [])
iabbrev fp fmt.Printf("\nDEBUG: %+v\n", abc)
"iabbrev pgv proplists:get_value(

nnoremap <leader>ve :tabnew $MYVIMRC<cr>
nnoremap <leader>vs :source ~/.vimrc<cr>

" surround a word or a visual block with "" (doesnt work with v-line)
vnoremap <leader>" <esc>`<i"<esc>`>la"
nnoremap <leader>" viw<esc>a"<esc>hbi"<esc>lel
inoremap <C-q> <Esc>viw<esc>a"<esc>hbi"<esc>lela
" surround a word or a visual block with {} (doesnt work with v-line)
vnoremap <leader>{ <esc>`<i}<esc>`>la{
nnoremap <leader>{ viw<esc>a}<esc>hbi{<esc>lel
inoremap <C-q> <Esc>viw<esc>a}<esc>hbi{<esc>lela
" surround a word or a visual block with {} (doesnt work with v-line)
vnoremap <leader>( <esc>`<i)<esc>`>la(
nnoremap <leader>( viw<esc>a)<esc>hbi(<esc>lel
inoremap <C-q> <Esc>viw<esc>a)<esc>hbi(<esc>lela
" surround a word or a visual block with {} (doesnt work with v-line)
vnoremap <leader>[ <esc>`<i]<esc>`>la[
nnoremap <leader>[ viw<esc>a]<esc>hbi[<esc>lel
inoremap <C-q> <Esc>viw<esc>a]<esc>hbi[<esc>lela

" surround a word or a visual block with '' (doesnt work with v-line)
vnoremap <leader>" <esc>`<i'<esc>`>la'
nnoremap <leader>' viw<esc>a'<esc>hbi'<esc>lel
noh
" Insert a character at the end of line
nnoremap <leader>, :normal! mqA,<esc>`q
nnoremap <leader>. :normal! mqA.<esc>`q
nnoremap <leader>; :normal! mqA;<esc>`q

" generate exuberant ctags for all directories excluding the assets directory
nnoremap <leader>ct :!ctags -R --exclude=assets *<cr>

augroup filetype_html
    autocmd!
    autocmd FileType,BufNewFile,BufRead *.mustache setlocal filetype=html
    au FileType *.mustache setl sw=2 sts=2
    au FileType html setl sw=2 sts=2
augroup END

let g:ycm_python_binary_path = 'python'
augroup filetype_python
    autocmd!
    autocmd FileType,BufNewFile,BufRead *.py setlocal filetype=python
    au BufNewFile,BufRead *.py  setl tabstop=2  softtabstop=2  shiftwidth=2  textwidth=80  expandtab  autoindent  fileformat=unix
    map <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>
    nnoremap <leader>o yiwoprint "<esc>pa: {}".format(<esc>pa)<esc>
augroup END

inoremap <C-h> <left>
inoremap <C-l> <right>
inoremap <C-j> <down>
inoremap <C-k> <up>
xnoremap . :norm.<CR>

" Move visual block (only for eye-candy)
vnoremap J :m '>+1<CR>gvgv
vnoremap K :m '<-2<CR>gvgv

let g:ref_use_vimproc = 1
let g:ref_open = 'split'
let g:ref_cache_dir = expand($TMP . '/vim_ref_cache/')
nno <leader>K :<C-u>Unite ref/erlang
            \ -vertical -default-action=split<CR>


nnoremap <leader>a :Ack! <C-r><C-w><cr>

set autowrite
set autowriteall

nmap <leader>p :set paste<cr>"*p:set nopaste<cr>
nmap <leader>np :set nopaste<cr>

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" local cd into the windows file
"autocmd BufEnter * silent! lcd %:p:h

set clipboard=unnamedplus

let g:ycm_key_list_select_completion=[]
let g:ycm_key_list_previous_completion=[]
let g:UltiSnipsExpandTrigger="<c-j>"

set exrc

let NERDSpaceDelims=1
let NERDDefaultAlign='left'

noremap <silent> <Leader>vS :<C-u>let @z=&so<CR>:set so=0 noscb<CR>:bo vs<CR>Ljzt:setl scb<CR><C-w>p:setl scb<CR>:let &so=@z<CR>

" modify selected text using combining diacritics
command! -range -nargs=0 Overline        call s:CombineSelection(<line1>, <line2>, '0305')
command! -range -nargs=0 Underline       call s:CombineSelection(<line1>, <line2>, '0332')
command! -range -nargs=0 DoubleUnderline call s:CombineSelection(<line1>, <line2>, '0333')
command! -range -nargs=0 Strikethrough   call s:CombineSelection(<line1>, <line2>, '0336')

function! s:CombineSelection(line1, line2, cp)
  execute 'let char = "\u'.a:cp.'"'
  execute a:line1.','.a:line2.'s/\%V[^[:cntrl:]]/&'.char.'/ge'
endfunction
